clients eligible for cervical cancer screening' - Age 25 to 49
palladiumkenya/openmrs-module-kenyaemr pull request #1667
Opened 2023-09-18 14:42 UTC by gabriel090

Add this  to the Clinical action report

It should include

Women within this age group who have never been screened for cervical cancer

Women within this age group who have had a screening done before but they are due for another screening based on the previous screening test and result

For clients previously screened using any other method except HPV and they had a negative result, they are eligible for rescreening after 12 months

For clients previously screened using HPV test and had a Negative result, they are eligible for rescreening after 2 years

NB: The client must be enrolled in HIV program and currently active on ART

2023-09-18 15:34 UTC, ojwanganto requested changes
@patryllus @njorocs can add more reviews. I don't have sufficient context

2023-09-18 15:34 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/CervicalCancerScreeningCalculation.java
> +    Integer NEGATIVE = 664;
we can make this name descriptive of its use. Negative is very generic

2023-09-18 15:34 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/CervicalCancerScreeningCalculation.java
> +        Set<Integer> alive = Filters.alive(cohort, context);
you can move this up and use it everywhere it is required

2023-10-18 05:52 UTC, patryllus approved these changes
Seems okay

2024-09-02 22:34 UTC, closed without merging