(feat) Add civilian categories for KDOD to match latest requirements
palladiumkenya/openmrs-module-kenyaemr pull request #1910
Opened 2024-05-23 13:36 UTC by donaldkibet

## Description

This PR add a new person attribute to support KDOD civilian runs. This is informed by KDOD request to customize the registration page,

```json
        "Veteran",
        "Dependant",
        "MOD Civilian",
        "DEFCO Civilian",
        "UPHS Civilian",
        "Other Civilian",
```

2024-05-23 14:43 UTC, makombe requested changes
@donaldkibet You need to go ahead and install the declared attribute something like this [this](https://github.com/palladiumkenya/openmrs-module-kenyaemr/blob/5670a288af4083f731e91a6c66c4c79223866868/api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java#L334)

2024-07-18 07:26 UTC, ojwanganto approved these changes

2024-07-18 07:33 UTC, makombe approved these changes

2024-07-18 07:34 UTC, makombe commented
@ojwanganto I this was for civilian. I will add the other for service

2024-07-18 07:34 UTC, merged