IDSR/DMI Flags optimization - removed 8 flags: combined them into IDSR flags for performance
palladiumkenya/openmrs-module-kenyaemr pull request #1940
Opened 2024-07-02 10:59 UTC by patryllus

![Screenshot from 2024-07-02 12-24-44](https://github.com/palladiumkenya/openmrs-module-kenyaemr/assets/1901372/dd7d476d-77e6-4c11-9d5a-c4cf920225bd)
![Screenshot from 2024-07-02 12-44-30](https://github.com/palladiumkenya/openmrs-module-kenyaemr/assets/1901372/6b600c35-b750-4939-80b4-bafd07d5f794)

2024-07-02 15:24 UTC, ojwanganto commented
Can we remove the repeated term 'suspected'? We may need to also add a way of separating the flag conditions.

2024-07-02 17:21 UTC, patryllus commented
![Screenshot from 2024-07-02 20-08-27](https://github.com/palladiumkenya/openmrs-module-kenyaemr/assets/1901372/91a89a18-9f28-41fe-bfec-3cb772d5ddee)

Made some updates

2024-07-08 14:23 UTC, ojwanganto requested changes
Thanks, @ojwanganto. I have left a few comments.

2024-07-08 14:23 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForIDSRFlagsCalculation.java
> +					if (patientJointPainResultTriage && patientFeverResultTriage) {
Let's have clear variable names i.e. triageEncounterHasJointPain or anything similar. Please check all the variables and update accordingly

2024-07-08 14:23 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForIDSRFlagsCalculation.java
> +										idsrMessage = idsrMessage.length() == 0 ? idsrMessage.append("Chikungunya ") : idsrMessage.append(",Chikungunya ");
You can extract the condition names into variables. We want to be DRY

2024-07-08 14:23 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForIDSRFlagsCalculation.java
> +	StringBuilder idsrMessage = new StringBuilder();
So that you don't have to do a lot of string concatenation, you can check on using a list of string and then join the elements using a ','.

2024-07-08 14:23 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForIDSRFlagsCalculation.java
> +	Integer SCREENING_QUESTION = 5219;
Let's use UUIDs instead

2024-07-24 17:02 UTC, closed without merging