Care ending reasons
palladiumkenya/openmrs-module-kenyaemr pull request #665
Opened 2020-10-28 11:56 UTC by njorocs

2020-11-03 10:53 UTC, patryllus reviewed
Kindly use SimpleObject instead of splitting a string.You can follow what Anto had done on IPT in greencard or getPatientsBookedOnDate still in grenncard

2020-11-03 10:54 UTC, patryllus requested changes
Use SimpleObject instead of split string like hoe its done in in greecard -> getPatientsBookedOnDate

2020-11-04 21:09 UTC, ojwanganto commented
@njorocs kindly address the issues raised. Thanks

2020-11-23 06:46 UTC, patryllus approved these changes

2020-11-23 06:46 UTC, merged