Updated NeedsViralLoadTestCalculation and NeedsViralLoadTestCalculationTest - removed LTFU
palladiumkenya/openmrs-module-kenyaemr pull request #948
Opened 2022-02-22 06:13 UTC by patryllus

2022-03-01 15:05 UTC, njorocs requested changes

2022-03-01 15:05 UTC, njorocs commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/UnSuppressedVLPatientsCalculation.java
> + * Calculates  patients are have unsuppressed VL results as last results given
Word the comment appropriately

2022-03-01 15:05 UTC, njorocs commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/art/MoreThanThreeMonthsOnARTCalculation.java
> + * Calculates  patients are have been on ART for more than 3 months (>3)
Word the comment appropriately

2022-03-01 15:05 UTC, njorocs commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/art/MoreThanThreeMonthsOnARTCalculation.java
> +	int monthsBetween(Date d1, Date d2) {
looks like a helper method. Can we move it to some common utils class?

2022-03-02 05:37 UTC, patryllus commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/IsBreastFeedingCalculation.java
> +		Concept BreastFeedingHivFollowupQuestion = Context.getConceptService().getConcept(5632);
Done

2022-03-02 05:39 UTC, patryllus commented on api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/art/MoreThanThreeMonthsOnARTCalculation.java
> + * Calculates  patients are have been on ART for more than 3 months (>3)
Deleted this file in subsequent PRs

2022-03-02 05:55 UTC, closed without merging